### ISSUE TITLE
Bring back `INCOMPLETE` status in derivatives bagel

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/digest#105]
See also https://github.com/neurodatascience/nipoppy/issues/176

### Steps to implement
- [x] add the `INCOMPLETE` status back to the pipeline status legend
- [x] add it back as a dropdown option under the "Advanced Filtering Options" part of the dashboard (for an imaging bagel, the available pipeline status options are currently hardcoded to discourage too many arbitrary values/stay aligned with the schema-defined `range`s, but this can be changed if desired)
- [x] add it back to the schema for an imaging bagel

(1) and (2) are highlighted in the screenshot below
<img width="950" alt="ui_overview_plots_annot" src="https://github.com/neurodatascience/nipoppy/assets/65699389/9d098bc2-acfc-4ab6-8795-4f635790fd8d">

**Comment by surchs** [comment]
looks fully specified to me.
