### ISSUE TITLE
Host dashboard using OpenStack instance instead of Render

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/digest#108]
- [x] Create new subdomain `digest.neurobagel.org` (see also https://github.com/neurobagel/proc_dash/issues/77) NGINX config file
- [x] Update NGINX config to route subdomain request to appropriate port
- [x] Request a SSL certificate (via CertBot) to enable HTTPS support
- [x] Delete custom subdomain for service on Render + suspend service
- [x] Update Namecheap record for  `digest.neurobagel.org` to point to `fairmount` IP
- [x] Install dependencies for and run dashboard on `fairmount` machine, NOT in debug mode:
  ```bash
  gunicorn digest.app:server -b :8050
  ```
- [x] Some extra config might be needed to allow large files to be processed:
  - By default, there's a 1MB limit on the request body - beyond that you get a `Request Entity Too Large` error
  ![image](https://github.com/neurobagel/digest/assets/65699389/8320ddda-17a0-48b9-bcbe-f73bb46f8643)
  - Solution: update Nginx Configuration:
    > Open your Nginx configuration file, which is usually located at /etc/nginx/nginx.conf or /etc/nginx/conf.d/default.conf. Look for the http block and add or update the client_max_body_size directive to a value that accommodates your needs. For example:
    > ```bash
    > http {
    >   client_max_body_size 20M;
    >     # Other configurations...
    > }
    > ```
  - This can be defined at the `server` block level for the `digest.neurobagel.org` config (since this is currently only relevant for this specific instance)
  - Refs:
    - https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by surchs** [comment]
@alyssadai is this already being worked on or is it more of a reminder / checklist issue?

**Comment by alyssadai** [comment]
Ah yes, I started to do some of the setup up until I encountered the `Request Entity Too Large` error, but forgot to move it into Implement - Active. Resuming this now.

**Comment by alyssadai** [comment]
For reviewer:

- Try accessing https://digest.neurobagel.org
- See nginx configuration file for digest.neurobagel.org on `fairmount` at `/etc/nginx/sites-available/digest.neurobagel.org`

**Comment by surchs** [comment]
@alyssadai do you have a .csv that is large (e.g. > 1MB)? Otherwise this looks great and good to go 🧑‍🍳

**Comment by alyssadai** [comment]
Sent via DM for your testing! Will close this for now.
